import 'package:get_it/get_it.dart';
import 'package:spotify_me/data/repositories/artists/artists_repository_iml.dart';
import 'package:spotify_me/data/source/artists/artists_itunes_service.dart';
import 'package:spotify_me/data/source/artists/artists_service.dart';
import 'package:spotify_me/data/source/song/song_itunes_service.dart';
import 'package:spotify_me/domain/repositories/artists/artists_repository.dart';
import 'package:spotify_me/domain/usecases/artists/get_artists.dart';
import 'package:spotify_me/domain/usecases/artists/get_artists_by_id.dart';
import 'package:spotify_me/domain/usecases/auth/logout.dart';
import 'package:spotify_me/domain/usecases/favourite/is_song_in_favourite.dart';
import 'package:spotify_me/domain/usecases/favourite/remove_song_favourite.dart';
import 'package:spotify_me/domain/usecases/song/search_song.dart';
import 'package:spotify_me/presentation/favourite/bloc/favourite_cubit.dart';
import 'package:spotify_me/data/repositories/auth/auth_repository_impl.dart';
import 'package:spotify_me/data/repositories/favourite/favourite_repository_iml.dart';
import 'package:spotify_me/data/repositories/song/song_repository_impl.dart';
import 'package:spotify_me/data/source/auth/auth_service.dart';
import 'package:spotify_me/data/source/auth/auth_supabase_service.dart';
import 'package:spotify_me/data/source/favoutire/favourite_service.dart';
import 'package:spotify_me/data/source/favoutire/favourite_supabase_iml.dart';
import 'package:spotify_me/data/source/song/song_service.dart';
import 'package:spotify_me/data/source/song/song_supabase_service.dart';
import 'package:spotify_me/domain/repositories/auth/auth.dart';
import 'package:spotify_me/domain/repositories/song/song_repository.dart';
import 'package:spotify_me/domain/usecases/auth/signin.dart';
import 'package:spotify_me/domain/usecases/auth/signup.dart';
import 'package:spotify_me/domain/repositories/favourite/favourite_repository.dart';
import 'package:spotify_me/domain/usecases/favourite/add_favourite_SongUsecase.dart';
import 'package:spotify_me/domain/usecases/favourite/get_favourite.dart';
import 'package:spotify_me/domain/usecases/song/get_news_songs.dart';
import 'package:spotify_me/presentation/home/bloc/new_songs_cubit/news_songs_cubit.dart';
import 'package:spotify_me/presentation/home/bloc/play_song_cubit/play_song_cubit.dart';
import 'package:spotify_me/presentation/home/widgets/PlaySongPages/Bloc/song_favourite_cubit.dart';
import 'package:spotify_me/presentation/home/widgets/PlaySongPages/Bloc/song_favourite_state.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

final sl = GetIt.instance;
Future<void> initializeDependencies() async {
  sl.registerSingleton<AuthService>(AuthSupabaseServiceImpl());
  sl.registerSingleton<ArtistsService>(ArtistsItunesService());
  sl.registerSingleton<SongService>(SongItunesService());
  sl.registerSingleton<AuthRepository>(AuthRepositoryImpl());
  sl.registerSingleton<SongRepository>(SongRepositoryImpl());
  sl.registerSingleton<ArtistsRepository>(ArtistsRepositoryIml());
  sl.registerSingleton<SignupUsecase>(SignupUsecase());
  sl.registerSingleton<SigninUsecase>(SigninUsecase());
  sl.registerSingleton<GetFavouriteUsecase>(GetFavouriteUsecase());
  sl.registerSingleton<GetNewsSongsUsecase>(GetNewsSongsUsecase());
  sl.registerSingleton<AddFavouriteSongUsecase>(AddFavouriteSongUsecase());
  sl.registerSingleton<LogoutUsecase>(LogoutUsecase());
  sl.registerSingleton<RemoveSongFavouriteUsecase>(
    RemoveSongFavouriteUsecase(),
  );
  sl.registerSingleton<IsSongInFavouriteUsecase>(IsSongInFavouriteUsecase());
  sl.registerSingleton<GetArtistsUsecase>(GetArtistsUsecase());
  sl.registerSingleton<GetArtistsByIdUsecase>(GetArtistsByIdUsecase());
  sl.registerSingleton<SupabaseClient>(Supabase.instance.client);
  sl.registerSingleton<FavouriteService>(FavouriteSupabaseIml());
  sl.registerSingleton<FavouriteRepository>(FavouriteRepositoryIml());
  sl.registerLazySingleton<FavouriteCubit>(() => FavouriteCubit());
  sl.registerLazySingleton<PlaySongCubit>(() => PlaySongCubit());
  sl.registerFactory<SongFavouriteCubit>(() => SongFavouriteCubit());
  sl.registerFactory<NewsSongsCubit>(() => NewsSongsCubit());
  sl.registerSingleton<SearchSongUsecase>(SearchSongUsecase());
}
